package project;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RTX
 */
public class borrowbook extends javax.swing.JFrame {

    Connection con;
    DefaultTableModel dtm;
    ArrayList<Integer> borrowIds = new ArrayList<>();//dynamic array >>refrence type
    ArrayList<Integer> bookIds = new ArrayList<>();//dynamic array >>refrence type
   
    public borrowbook() {
        initComponents();
        this.setLocationRelativeTo(null);
        borrowbook();
        dtm = new DefaultTableModel();
        dtm.addColumn("Section");
        dtm.addColumn("Name");
        dtm.addColumn("Cost");
        dtm.addColumn("Num of Days");
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root", "mo992004");
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillcombo_section();
         modelTable();
    }

    public void borrowbook() {
        ImageIcon icon = new ImageIcon("D:\\Project\\src\\images\\Login_img.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(background.getWidth(), background.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon = new ImageIcon(imgScale);
        background.setIcon(scaleIcon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_cost = new javax.swing.JLabel();
        spin_n_days = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        combo_section = new javax.swing.JComboBox<>();
        combo_book = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_show = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(120, 340, 85, 33);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Borrow Book");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 0, 149, 32);

        lbl_cost.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_cost.setText("0$");
        jPanel1.add(lbl_cost);
        lbl_cost.setBounds(70, 190, 160, 20);

        spin_n_days.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_n_daysStateChanged(evt);
            }
        });
        jPanel1.add(spin_n_days);
        spin_n_days.setBounds(110, 130, 130, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("No of days:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 130, 89, 34);

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add);
        btn_add.setBounds(40, 290, 94, 33);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("cost :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 180, 50, 39);

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(190, 290, 94, 33);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(90, 30, 140, 10);

        combo_section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_sectionActionPerformed(evt);
            }
        });
        jPanel1.add(combo_section);
        combo_section.setBounds(98, 50, 240, 22);
        jPanel1.add(combo_book);
        combo_book.setBounds(98, 90, 240, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Section :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 50, 70, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Book :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 90, 60, 22);
        jPanel1.add(background);
        background.setBounds(-10, 0, 360, 410);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tbl_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Book", "Cost", "Num"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_show);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Coustumer obj = new Coustumer();
        dispose();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void spin_n_daysStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_n_daysStateChanged
        // TODO add your handling code here:
        if ((Integer) spin_n_days.getValue() <= 0) {
            spin_n_days.setValue(1);
        }

        int x = ((Integer) spin_n_days.getValue()) * 2;
        lbl_cost.setText(x + "$");
    }//GEN-LAST:event_spin_n_daysStateChanged

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        if (lbl_cost.getText().length() == 0 || (Integer) spin_n_days.getValue() <= 0) {
            JOptionPane.showMessageDialog(this, " not added /n Fields is empty", "confirmation", 0);
            return;
        }
        try {
            
            String book_name= combo_book.getSelectedItem().toString();//book name
             String book_section= combo_section.getSelectedItem().toString();//book section
            String cost = lbl_cost.getText();
            String num = spin_n_days.getValue().toString();
            int cbxbb_selected = combo_book.getSelectedIndex();
            
            PreparedStatement st = con.prepareStatement("insert into borrow_book (bobook_book,bobook_cost,bobook_num_pages,bobook_section) values (?,?,?,?) ");
          
            st.setString(1,book_name);
            st.setString(2, cost);
            st.setString(3, num);
             st.setString(4,book_section);
            // st.setInt(4, bookIds.get(cbxbb_selected));
            st.executeUpdate();
            select();
            modelTable();
            JOptionPane.showMessageDialog(this, "Book Added", "confirmation", 1);
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btn_addActionPerformed
    private void modelTable() {
        try {
            dtm.setRowCount(0);//for empty default model
            PreparedStatement stmt = con.prepareStatement("select bobook_id,bobook_section,bobook_book,bobook_cost,bobook_num_pages from borrow_book");
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {

                borrowIds.add(rs.getInt(1));
                dtm.addRow(new Object[]{rs.getString(2),rs.getString(3), rs.getString(4), rs.getString(5)});
            }
            tbl_show.setModel(dtm);

        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }
    private void combo_sectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_sectionActionPerformed
        // TODO add your handling code here:
        combo_book.removeAllItems();
        fillcombo_book(combo_section.getSelectedItem().toString());
    }//GEN-LAST:event_combo_sectionActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          select();
        try {
            // TODO add your handling code here:
            PreparedStatement stmt = con.prepareStatement("delete from borrow_book  where bobook_id=?");
            stmt.setInt(1, tbl_show.getSelectedRow()+1);

            stmt.executeUpdate();
            modelTable();
            JOptionPane.showMessageDialog(this, "Deleted Succeded");
        } catch (SQLException ex) {
            Logger.getLogger(borrowbook.class.getName()).log(Level.SEVERE, null, ex);
        }
        select();
       
    }//GEN-LAST:event_jButton3ActionPerformed
     private void update(int x , int i){
        try {
            PreparedStatement stmt = con.prepareStatement("update borrow_book set bobook_id=? where bobook_id=?");
            stmt.setInt(1, i);
            stmt.setInt(2, x);
            stmt.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(book.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void select(){
        try {
            int i=1;
            PreparedStatement stmt = con.prepareStatement("select bobook_id from borrow_book");
            ResultSet rs = stmt.executeQuery();
            while (rs.next() && !rs.wasNull()) {
                update(rs.getInt(1),i);
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(book.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void fillcombo_section() {
        try {
            
             combo_section.removeAllItems();
             Set<String> uniqueSections = new LinkedHashSet<>();
             combo_book.removeAllItems();
            dtm.setRowCount(0);//for empty default model
            PreparedStatement stmt = con.prepareStatement("select book_id,book_section from book");
            ResultSet rs = stmt.executeQuery();
            while (rs.next() && !rs.wasNull()) {
                String section = rs.getString("book_section");
             if (!uniqueSections.contains(section)) {
                 uniqueSections.add(section);
                combo_section.addItem(section);
            }
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        fillcombo_book(combo_section.getSelectedItem().toString());
    }

    private void fillcombo_book(String sec) {
        try {
            combo_book.removeAllItems();
            PreparedStatement st = con.prepareStatement("select * from book where book_section=?");
            st.setString(1, sec);
            ResultSet rs;
            rs = st.executeQuery();
            while (rs.next()) {
                bookIds.add(rs.getInt(1));
                combo_book.addItem(rs.getString(2));
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(Buybook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(borrowbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(borrowbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(borrowbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(borrowbook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new borrowbook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_add;
    private javax.swing.JComboBox<String> combo_book;
    private javax.swing.JComboBox<String> combo_section;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_cost;
    private javax.swing.JSpinner spin_n_days;
    private javax.swing.JTable tbl_show;
    // End of variables declaration//GEN-END:variables
}
